FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build

WORKDIR /app

RUN dotnet new console -n consumer
WORKDIR /app/consumer

RUN dotnet add package Confluent.Kafka

COPY consumer/Program.cs ./

RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS runtime
WORKDIR /app
COPY --from=build /app/consumer/out ./

ENTRYPOINT ["dotnet", "consumer.dll"]
